spring:
  application:
    name: BooksServiceRegistry

  profiles:
    active: default

  cloud:
    loadbalancer:
      ribbon:
        enabled: false    # RibbonLoadBalancerClient deprecated. This setting uses BlockingLoadBalancerClient

server:
  port: 8761

eureka:
  server:
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: ${SERVICE_REGISTRY}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://$
      {eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        # Exposing only read only items and not large data amounts - so no heapdump, threaddump or shutdown. No project use of flyway, integrationgraph, liquibase, prometheus
        include: auditevents, beans, caches, conditions, configprops, env, health, httptrace, info, jolokia, logfile, loggers, metrics, mappings, scheduledtasks, sessions
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false