spring:
  application:
    name: BooksServiceRegistry
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8761

eureka:
  server:
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
