spring:
  application:
    name: BooksServiceRegistry

  profiles:
    active: default

  cloud:
    loadbalancer:
      ribbon:
        enabled: false    # RibbonLoadBalancerClient deprecated. This setting uses BlockingLoadBalancerClient

server:
  port: 8761

eureka:
  server:
    eviction-interval-timer-in-ms: 60000
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
